### ISSUE TITLE
issue with Travis ?

### ISSUE THREAD

**Issue by thibautjombart** [Hackout2/format#1]
Travis currently complains about a missing configuration file. Need to check that the relevant files were added - use_travis() in devtools.

**Comment by thibautjombart** [comment]
Note: it may also be that the Travis files weren't committed / pushed.

**Comment by anabento** [comment]
Ok, I will have a look this afternoon! 

Sent from my iPhone

On 18 Feb 2015, at 09:37, Thibaut Jombart notifications@github.com wrote:

Note: it may also be that the Travis files weren't committed / pushed.

**Comment by andysouth** [comment]
I have fixed this one. Now it fails for other reasons that we were aware of. I'll look at this week.

**Comment by anabento** [comment]
Thanks Andy. 

Sent from my iPhone

On 18 Feb 2015, at 10:27, AndySouth notifications@github.com wrote:

I have fixed this one. Now it fails for other reasons that we were aware of. I'll look at this week.

**Comment by thibautjombart** [comment]
Great, thanks !

**Comment by andysouth** [comment]
Wehay! Package now passes check.

**Comment by anabento** [comment]
:)

Sent from my iPhone

On 18 Feb 2015, at 18:26, AndySouth notifications@github.com wrote:

Wehay! Package now passes check.

**Comment by thibautjombart** [comment]
This is great, well done! =D
